### PR TITLE
Pet improvements and bug fixes

### PR DESCRIPTION
**Pull request by mooziii**

### CODE REVIEW

**Comment by mooziii** [comment]
i have to rework a bit to fix this bug.

**Review by mooziii — COMMENTED** [review]
haha bitte nicht fragen war bisschen durcheinander weil hotkey in der zwischenzeit noch was gemacht hatte

**Comment by jakobkmar** [comment]
is this pull request ready for merge now?

**Comment by mooziii** [comment]
> 
> 
> is this pull request ready for merge now?

yes

**Review by jakobkmar — APPROVED** [review]

**Pull request merged**
